import type { Invariant } from '../lib/invariants.ts';

export const COVERED_INVARIANTS = {
  lifecycle: [],
  parseErrors: [
    'frontmatter-unknown-key',
    'frontmatter-missing-key',
    'frontmatter-slug',
    'section-missing',
    'section-unknown',
    'frontmatter-line-unparseable',
    'frontmatter-unterminated',
    'frontmatter-missing',
    'frontmatter-status',
    'frontmatter-current-phase',
    'frontmatter-current-step',
    'frontmatter-commits-authorized',
    'frontmatter-created',
    'section-out-of-order',
    'plan-line-unparseable',
    'list-line-unparseable',
    'constraint-line-unparseable',
    'decision-line-unparseable',
    'decision-empty-field',
    'verification-status-missing',
    'verification-status-invalid',
    'automated-checks-missing',
    'automated-checks-too-many-items',
    'automated-checks-invalid',
    'verification-manual-missing',
    'verification-manual-too-many-items',
    'verification-manual-invalid',
    'progress-step-missing',
    'progress-status-missing',
    'progress-status-invalid',
    'manual-verification-missing',
    'manual-verification-too-many-items',
    'manual-verification-invalid',
    'goal-missing',
  ],
  appendOnly: [
    'append-only-entry-modified',
    'append-only-entry-removed',
  ],
  planProgress: [
    'progress-duplicate-step',
    'progress-complete-with-manual-needed',
    'progress-complete-with-failed-checks',
    'progress-checks-passed-mismatch',
    'plan-unchecked-with-complete-progress',
    'plan-empty-after-plan-phase',
    'acceptance-criteria-empty-after-plan-phase',
    'progress-step-not-in-plan',
    'plan-checked-without-progress',
  ],
  phase: [
    'phase-precondition-unaccounted-prior-phase',
    'phase-accounting-missing-decision',
    'phase-accounting-skipped-phase-has-output',
    'phase-accounting-non-self-gated-skip',
    'selected-step-not-in-plan',
    'selected-step-current-step-mismatch',
    'close-without-verification-pass',
    'phase-accounting-future-phase-decision',
    'phase-accounting-ran-phase-missing-output',
    'phase-precheck-without-workspace-path',
    'phase-precondition-missing-file',
    'prep-with-active-current-step',
    'implement-without-current-step',
    'verify-without-progress',
    'verify-with-active-current-step',
    'verify-with-manual-verification-needed',
    'selected-step-missing',
    'selected-step-multiple',
  ],
  status: [
    'not-started-with-current-phase',
    'not-started-with-current-step',
    'current-step-before-prep',
    'constraint-future-phase-tag',
    'constraint-invalid-tag',
    'in-planning-with-checked-plan',
    'in-planning-with-progress',
    'in-progress-before-prep',
    'blocked-without-conflicts',
    'conflicts-without-blocked-status',
    'status-complete-missing-what-we-built',
    'what-we-built-premature',
    'current-step-stale',
    'current-step-not-in-plan',
    'current-step-not-active',
    'planning-with-unresolved-unknowns',
    'complete-without-close',
    'complete-without-verification-pass',
    'abandoned-without-decision-rationale',
  ],
  verification: [
    'verification-pass-with-active-current-step',
    'verification-pass-without-latest-complete-progress',
    'verification-pass-with-manual-verification-deferred-without-decision',
    'verification-pass-with-unchecked-plan',
    'verification-pass-with-unmet-acceptance-criteria',
    'verification-pass-with-conflicts',
    'verification-pass-without-automated-checks',
    'verification-pass-without-manual-verification',
  ],
} satisfies Record<string, readonly Invariant[]>;
